---
name: create-pr

on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
      author:
        required: true
        type: string
      aqua_version:
        required: true
        type: string

      title:
        required: false
        type: string
        default: 'docs: generate document by yodoc'
      commit_message:
        required: false
        type: string
        default: 'docs: generate document by yodoc'
      branch_prefix:
        required: false
        type: string
        default: generate-doc-
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true

jobs:
  check-create-pr:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      pr_url: ${{fromJson(steps.pr.outputs.payload).html_url}}
      pr_number: ${{steps.pr.outputs.number}}
      pr_author: ${{fromJson(steps.pr.outputs.payload).user.login}}
      ignored: |
        ${{fromJson(steps.pr.outputs.payload).user.login == inputs.author && steps.pr.outputs.title == inputs.title}}
    steps:
      - uses: suzuki-shunsuke/gh-find-current-pr@52df560f9181a2d5aaffd3b6934f5921b48920f4
        id: pr
        with:
          state: closed
      - run: |
          echo "LOGIN: $LOGIN"
          echo "TITLE: $TITLE"
          echo "PR URL: $PR_URL"
          echo "PR Number: $PR_NUMBER"
          echo "PR Author: $PR_AUTHOR"
        env:
          LOGIN: ${{fromJson(steps.pr.outputs.payload).user.login}}
          TITLE: ${{steps.pr.outputs.title}}
          PR_NUMBER: ${{steps.pr.outputs.number}}
          PR_URL: ${{fromJson(steps.pr.outputs.payload).html_url}}
          PR_AUTHOR: ${{fromJson(steps.pr.outputs.payload).user.login}}

  create-pr:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    needs: check-create-pr
    permissions: {}
    # prevent infinite loop
    if: |
      !fromJson(needs.check-create-pr.outputs.ignored)
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: ${{inputs.aqua_version}}
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
          # create a pull request
          # create a branch
          permissions: >-
            {
              "pull_requests": "write",
              "contents": "write"
            }
          repositories: >-
            [
              "${{github.event.repository.name}}"
            ]
      - run: git grep -l -E '^<!-- This file is generated by yodoc.' | xargs -r rm
      - run: yodoc run
      - run: echo branch="${BRANCH_PREFIX}$(date +%Y%m%dT%H%M%S)" >> "$GITHUB_OUTPUT"
        id: branch
        env:
          BRANCH_PREFIX: ${{inputs.branch_prefix}}
      - run: |
          deleted_files=$(mktemp)
          changed_files=$(mktemp)
          echo "deleted_files=$deleted_files" >> "$GITHUB_OUTPUT"
          echo "changed_files=$changed_files" >> "$GITHUB_OUTPUT"
          git diff --name-only --diff-filter=D > "$deleted_files"
          git diff --name-only --diff-filter=d > "$changed_files"
          git ls-files --others --exclude-standard >> "$changed_files"
          if test -s "$changed_files"; then
            echo changed=true >> "$GITHUB_OUTPUT"
          fi
          if test -s "$deleted_files"; then
            echo deleted=true >> "$GITHUB_OUTPUT"
          fi
        id: changed

      - run: |
          if [ "$CHANGED" = true ] && [ "$DELETED" = true ]; then
            ghcp commit \
              -r "$GITHUB_REPOSITORY" \
              -b "$BRANCH" \
              -m "$MESSAGE" \
              --delete-file "$DELETED_FILES" \
              $(cat "$CHANGED_FILES")
            exit 0
          fi
          if [ "$CHANGED" = true ]; then
            ghcp commit \
              -r "$GITHUB_REPOSITORY" \
              -b "$BRANCH" \
              -m "$MESSAGE" \
              $(cat "$CHANGED_FILES")
            exit 0
          fi
          ghcp commit \
            -r "$GITHUB_REPOSITORY" \
            -b "$BRANCH" \
            -m "$MESSAGE" \
            --delete-file "$DELETED_FILES"
        if: |
          steps.changed.outputs.changed == 'true' || steps.changed.outputs.deleted == 'true'
        env:
          MESSAGE: ${{inputs.commit_message}}
          CHANGED_FILES: ${{steps.changed.outputs.changed_files}}
          DELETED_FILES: ${{steps.changed.outputs.deleted_files}}
          GITHUB_TOKEN: ${{steps.token.outputs.token}}
          BRANCH: "${{steps.branch.outputs.branch}}"
          CHANGED: "${{steps.changed.outputs.changed}}"
          DELETED: "${{steps.changed.outputs.deleted}}"
      - run: |
          body="This pull request was created by [yodoc](https://github.com/suzuki-shunsuke/yodoc).
          [GitHub Actions]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)
          [Pull Request]($PR_URL)"
          gh pr create \
            -t "$TITLE" \
            -b "$body" \
            -B "$BASE_BRANCH" \
            -H "$BRANCH"
        if: |
          steps.changed.outputs.changed == 'true' || steps.changed.outputs.deleted == 'true'
        env:
          BASE_BRANCH: ${{inputs.base_branch}}
          TITLE: ${{inputs.title}}
          GITHUB_TOKEN: ${{steps.token.outputs.token}}
          BRANCH: "${{steps.branch.outputs.branch}}"
          PR_URL: "${{needs.check-create-pr.outputs.pr_url}}"

      - run: |
          github-comment post \
             -var "pr_author:$PR_AUTHOR" \
             -template "$TEMPLATE"
        if: failure()
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}
          GH_COMMENT_PR_NUMBER: ${{needs.check-create-pr.outputs.pr_number}}
          PR_AUTHOR: ${{needs.check-create-pr.outputs.pr_author}}
          TEMPLATE: |
            ## :x: Failed to generate document

            @{{.Vars.pr_author}}
            
            Please check the failed workflow run.

            {{template 'link' .}}
